# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/coki/fer_projects/bioinf_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/coki/fer_projects/bioinf_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/coki/fer_projects/bioinf_project/CMakeFiles /home/coki/fer_projects/bioinf_project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/coki/fer_projects/bioinf_project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bioinf

# Build rule for target.
bioinf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bioinf
.PHONY : bioinf

# fast build rule for target.
bioinf/fast:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/build
.PHONY : bioinf/fast

FastaParser.o: FastaParser.cpp.o

.PHONY : FastaParser.o

# target to build an object file
FastaParser.cpp.o:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/FastaParser.cpp.o
.PHONY : FastaParser.cpp.o

FastaParser.i: FastaParser.cpp.i

.PHONY : FastaParser.i

# target to preprocess a source file
FastaParser.cpp.i:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/FastaParser.cpp.i
.PHONY : FastaParser.cpp.i

FastaParser.s: FastaParser.cpp.s

.PHONY : FastaParser.s

# target to generate assembly for a file
FastaParser.cpp.s:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/FastaParser.cpp.s
.PHONY : FastaParser.cpp.s

MleEstimator.o: MleEstimator.cpp.o

.PHONY : MleEstimator.o

# target to build an object file
MleEstimator.cpp.o:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/MleEstimator.cpp.o
.PHONY : MleEstimator.cpp.o

MleEstimator.i: MleEstimator.cpp.i

.PHONY : MleEstimator.i

# target to preprocess a source file
MleEstimator.cpp.i:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/MleEstimator.cpp.i
.PHONY : MleEstimator.cpp.i

MleEstimator.s: MleEstimator.cpp.s

.PHONY : MleEstimator.s

# target to generate assembly for a file
MleEstimator.cpp.s:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/MleEstimator.cpp.s
.PHONY : MleEstimator.cpp.s

Sequence.o: Sequence.cpp.o

.PHONY : Sequence.o

# target to build an object file
Sequence.cpp.o:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/Sequence.cpp.o
.PHONY : Sequence.cpp.o

Sequence.i: Sequence.cpp.i

.PHONY : Sequence.i

# target to preprocess a source file
Sequence.cpp.i:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/Sequence.cpp.i
.PHONY : Sequence.cpp.i

Sequence.s: Sequence.cpp.s

.PHONY : Sequence.s

# target to generate assembly for a file
Sequence.cpp.s:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/Sequence.cpp.s
.PHONY : Sequence.cpp.s

Viterbi.o: Viterbi.cpp.o

.PHONY : Viterbi.o

# target to build an object file
Viterbi.cpp.o:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/Viterbi.cpp.o
.PHONY : Viterbi.cpp.o

Viterbi.i: Viterbi.cpp.i

.PHONY : Viterbi.i

# target to preprocess a source file
Viterbi.cpp.i:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/Viterbi.cpp.i
.PHONY : Viterbi.cpp.i

Viterbi.s: Viterbi.cpp.s

.PHONY : Viterbi.s

# target to generate assembly for a file
Viterbi.cpp.s:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/Viterbi.cpp.s
.PHONY : Viterbi.cpp.s

ViterbiLogOdds.o: ViterbiLogOdds.cpp.o

.PHONY : ViterbiLogOdds.o

# target to build an object file
ViterbiLogOdds.cpp.o:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/ViterbiLogOdds.cpp.o
.PHONY : ViterbiLogOdds.cpp.o

ViterbiLogOdds.i: ViterbiLogOdds.cpp.i

.PHONY : ViterbiLogOdds.i

# target to preprocess a source file
ViterbiLogOdds.cpp.i:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/ViterbiLogOdds.cpp.i
.PHONY : ViterbiLogOdds.cpp.i

ViterbiLogOdds.s: ViterbiLogOdds.cpp.s

.PHONY : ViterbiLogOdds.s

# target to generate assembly for a file
ViterbiLogOdds.cpp.s:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/ViterbiLogOdds.cpp.s
.PHONY : ViterbiLogOdds.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/bioinf.dir/build.make CMakeFiles/bioinf.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... bioinf"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... FastaParser.o"
	@echo "... FastaParser.i"
	@echo "... FastaParser.s"
	@echo "... MleEstimator.o"
	@echo "... MleEstimator.i"
	@echo "... MleEstimator.s"
	@echo "... Sequence.o"
	@echo "... Sequence.i"
	@echo "... Sequence.s"
	@echo "... Viterbi.o"
	@echo "... Viterbi.i"
	@echo "... Viterbi.s"
	@echo "... ViterbiLogOdds.o"
	@echo "... ViterbiLogOdds.i"
	@echo "... ViterbiLogOdds.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

